### ISSUE TITLE
LazyMan IOS15

### ISSUE THREAD

**Issue by IceBear16** [inickt/LazyMan-iOS#83]
The video player for MLB on IOS15 repeatedly freezes when going to full screen.

**Comment by inickt** [comment]
I released [v1.3.0](https://github.com/inickt/LazyMan-iOS/releases/tag/v1.3.0), can you let me know if you are still having the issue? If you are, a screen recording would be super helpful as well.

**Comment by fkick** [comment]
![IMG_9871](https://user-images.githubusercontent.com/8224667/136853756-719f4aab-4e70-40da-91cd-523ae7ffc155.PNG)

No issues with Airplay on my end once a feed is playing and no issue with Casting Audio to my Google devices.

**Comment by inickt** [comment]
Chomecast should now be working.

Follow the mirroring steps here: https://support.apple.com/en-us/HT204289

**Comment by IceBear16** [comment]
So the chromecast does work now but only with the default audio, when I try and change to radio, the cast stops and I need to restart the app. For Airplay, It still doesn't work unless I screen mirror. Does Airplay not work except for screen mirroring?
